name: amap_map_fluttify_example
description: Demonstrates how to use the amap_map_fluttify plugin.
publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  permission_handler: ^4.4.0+hotfix.2
  oktoast: ^2.3.1+1
  decorated_flutter: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  amap_map_fluttify:
    path: ../

flutter:
  uses-material-design: true
  assets:
    - images/
    - raw/