name: amap_map_fluttify
description: An `Amap` map component, based on `fluttify` engine.
version: 0.2.3+61475ac
author: yohom <382146139@qq.com>
homepage: https://github.com/fluttify-project/amap_map_fluttify

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  amap_core_fluttify: ^0.0.6
  foundation_fluttify: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: me.yohom.amap_map_fluttify
    pluginClass: AmapMapFluttifyPlugin